name: tf
channels:
- defaults
- anaconda
- conda-forge
dependencies:
- cudatoolkit=10.2
- tensorflow=2.4.1
- python==3.8
- keras
- numpy
- pandas
- matplotlib
- urllib3
- scikit-learn
- jupyter 
- jupyterlab
- pip
- pip:
  - nbdev
  - tensorflow-datasets
  - tensorflow-text
