name: dl
channels:
- defaults
- anaconda
dependencies:
- cudatoolkit
- tensorflow
- keras
- numpy
- pandas
- matplotlib
- urllib3
- scikit-learn
- pip: 
  - nbdev
  - tensorflow-datasets
  - tensorflow-text
  